POST http://localhost:4000/verifyCodeLoginForAdmin HTTP/1.1
content-type: application/json
Authorization: token xxx

{
    "code": "86596",
}



# When content type of request body is multipart/form-data, you may have the mixed format of the request body as follows:

# POST https://api.example.com/user/upload
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="text"

# title
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="image"; filename="1.png"
# Content-Type: image/png

# < ./1.png
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--